### ISSUE TITLE
Words that use concept dict mapper break the website

### ISSUE THREAD

**Issue by danich1** [greenelab/word-lapse#32]
After merging words such as "pandemic" and "rna" break the website. I think there might be in issue on the backend or frontend, but overall I'm not sure what is happening. Just wanted to open this issue in-case you aren't aware.

**Comment by falquaddoomi** [comment]
Seems like it was a caching issue: the backend was returning results in the old string format, rather than the new `{ token, tagged_id }` format. I cleared the cache and rebooted everything and it appears to be working, but let me know if you're still seeing funny behavior. I'm also going to add an exception to that temporary fix code to just return the value if there's no `token` entry in the object (i.e., if it's a string) to be a little bit more resilient to cached results people might have in their browsers, etc.

**Comment by falquaddoomi** [comment]
FYI, just added that exception in https://github.com/greenelab/word-lapse/commit/0a6a55a9c0c9e62e802efe8af95be01cc89103db.
